name: flutter_file

description: "A new Flutter project."
publish_to: 'none' 



environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  file_picker: ^8.0.3
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0







flutter:


  uses-material-design: true


